### PR TITLE
guard for unmounted component when resolving/rejecting the promise

### PR DESCRIPTION
**Pull request by capaj**

### CODE REVIEW

**Comment by tsirlucas** [comment]
Dude you forgot to accept the PR (I think)

**Comment by capaj** [comment]
@tsirlucas thanks for the reminder

**Comment by tsirlucas** [comment]
You're welcome! If you could create a npm version, I would be really grateful.

**Comment by capaj** [comment]
@tsirlucas released as 2.0.1

**Comment by tsirlucas** [comment]
Thanks!

**Pull request merged**
