### PR TITLE
Add Typescript definitions

### PR DESCRIPTION
**Pull request by icopp**
This adds some basic Typescript definitions for anybody using the project with `tsx` files, and a note in the README on how to use it.

### CODE REVIEW

**Comment by gschjetne** [comment]
@capaj can you please make a release that includes this?

**Comment by gschjetne** [comment]
I'll also add that `async.d.ts` doesn't seem to show up in `lib/` as indicated by `package.json`.

**Comment by capaj** [comment]
@gschjetne will do

**Comment by capaj** [comment]
@gschjetne just published 1.2.0, try it out. Replaced webpack with rollup while I was at it.

**Comment by gschjetne** [comment]
Thanks!

**Pull request merged**
